$ErrorActionPreference = "Stop"

# Ensure data directory exists
$DATA_DIR = Join-Path $PSScriptRoot "data"
if (-not (Test-Path $DATA_DIR)) {
    Write-Host "Creating data directory..." -ForegroundColor Cyan
    New-Item -ItemType Directory -Path $DATA_DIR | Out-Null
}

# Cleanup zombie processes on core ports (Server 7070, Mongo 27017)
Write-Host "Cleaning up zombie processes on ports 7070 and 27017..." -ForegroundColor Cyan
$Ports = @(7070, 27017)
foreach ($Port in $Ports) {
    $connections = Get-NetTCPConnection -LocalPort $Port -ErrorAction SilentlyContinue
    foreach ($conn in $connections) {
        $processId = $conn.OwningProcess
        if ($processId -gt 0) {
            try {
                Write-Host "Killing process $processId on port $Port..." -ForegroundColor Yellow
                Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue
            } catch {}
        }
    }
}


# Setup Java Environment
$TargetJavaHome = "C:\Program Files\Eclipse Adoptium\jdk-17.0.18.8-hotspot"

if (-not $env:JAVA_HOME -or -not (Test-Path $env:JAVA_HOME)) {
    if (Test-Path $TargetJavaHome) {
        $env:JAVA_HOME = $TargetJavaHome
    } else {
        # Try to find any JDK in common locations
        $PossiblePaths = @(
            "$PSScriptRoot\tools\jdk\jdk-*",
            "C:\Program Files\Eclipse Adoptium\jdk-*",
            "C:\Program Files\Microsoft\jdk-*",
            "C:\Program Files\Java\jdk-*",
            "C:\Program Files\Android\openjdk\jdk-*"
        )
        $FoundPath = Get-Item $PossiblePaths -ErrorAction SilentlyContinue | Sort-Object Name -Descending | Select-Object -First 1
        if ($FoundPath) {
            $env:JAVA_HOME = $FoundPath.FullName
        }
    }
}

if ($env:JAVA_HOME -and (Test-Path $env:JAVA_HOME)) {
    $env:Path = "$env:JAVA_HOME\bin;" + $env:Path
    Write-Host "Using JAVA_HOME: $env:JAVA_HOME" -ForegroundColor Gray
} else {
    Write-Error "JAVA_HOME not found. Please install a JDK (version 11 or higher)."
    exit 1
}

$SERVER_DIR = "$PSScriptRoot\server"

# Run generate_protos.ps1 to handle protobuf generation (like generate_protos.sh on Unix)
Write-Host "Generating Protobuf files..." -ForegroundColor Cyan
Set-Location $SERVER_DIR
& powershell -ExecutionPolicy Bypass -File generate_protos.ps1

Write-Host "Starting Server..." -ForegroundColor Green
Set-Location $SERVER_DIR

# Find mvn.cmd
$MvnCmd = Get-Command mvn.cmd -ErrorAction SilentlyContinue
if ($null -eq $MvnCmd) {
    # Try common installation paths if not in PATH
    $CommonPaths = @(
        "$PSScriptRoot\tools\maven\apache-maven-*\bin\mvn.cmd",
        "$PSScriptRoot\..\racecoordinator_ai\tools\maven\apache-maven-*\bin\mvn.cmd",
        "C:\Maven\apache-maven-*\bin\mvn.cmd",
        "C:\Program Files\apache-maven-*\bin\mvn.cmd",
        "C:\maven\bin\mvn.cmd"
    )
    $MvnCmd = Get-Item $CommonPaths -ErrorAction SilentlyContinue | Select-Object -First 1
}

if ($null -eq $MvnCmd) {
    Write-Warning "mvn.cmd not found in PATH or common locations. Falling back to 'mvn'."
    $MvnExecutable = "mvn"
} else {
    if ($MvnCmd -is [System.IO.FileInfo]) {
        $MvnExecutable = $MvnCmd.FullName
    } else {
        $MvnExecutable = "mvn.cmd"
    }
}

$DATA_DIR = Join-Path $PSScriptRoot "data"
# -T 1C: Parallel build (1 thread per core)
# -Dmaven.test.skip=true: Skip tests for faster development cycle
# -DskipProtobuf=true: Protos are already generated by generate_protos.ps1
$MvnArgs = @("-T", "1C", "compile", "exec:java", "-Dexec.mainClass=com.antigravity.App", "-Dapp.data.dir=$DATA_DIR", "-DskipProtobuf=true", "-Dmaven.test.skip=true")
& $MvnExecutable @MvnArgs
